[package]

name = "rscam"
version = "0.3.10"
description = "Wrapper for v4l2."
keywords = ["v4l2", "video", "camera", "capture"]
authors = ["Paul Loyd <pavelko95@gmail.com>"]
repository = "https://github.com/loyd/rscam"
documentation = "http://loyd.github.io/rscam"
license = "MIT"
readme = "README.md"

[features]

no_wrapper = []
